name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-pipeline:
    needs: sonarcloud
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      OPENLINEAGE_DISABLED: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          cd openfilter
          pip install poetry
          poetry env use python3
          poetry install --no-root
          timeout 30s poetry run python src/openfilter/script.py || echo "Pipeline finished or timed out"
        env:
          PYTHONPATH: ${{ github.workspace }}/openfilter/src
            
      - name: Show OCR Output
        run: |
          echo "OCR results:"
          cat openfilter/output/ocr_results.json || echo "No OCR output found."